//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWorkspace.ListViewer.VisualWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class WorkspaceListViewWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal ScriptParamLiteral;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(WorkspaceListViewWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlScriptParamLiteral() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ScriptParamLiteral = @__ctrl;
            @__ctrl.ID = "ScriptParamLiteral";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::ProjectWorkspace.ListViewer.VisualWebPart.WorkspaceListViewWebPart @__ctrl) {
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControlScriptParamLiteral();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    (function () {\r\n        if (this.epmva" +
                        "r) {\r\n            if (typeof jQuery == \'undefined\') {\r\n                var jquer" +
                        "yPath = getProjectSiteViewerComponent(\'jquery-1.10.2.min.js\');\r\n                " +
                        "document.write(\'<script type=\"text/javascript\" src=\"\' + jqueryPath + \'\"><\\/scrip" +
                        "t>\');\r\n            }\r\n            if (typeof epm == \'undefined\') {\r\n            " +
                        "    var epmPath = getProjectSiteViewerComponent(\'projectsitelistviewer.js\');\r\n  " +
                        "              document.write(\'<script type=\"text/javascript\" src=\"\' + epmPath + " +
                        "\'\"><\\/script>\');\r\n            }\r\n            function getProjectSiteViewerCompon" +
                        "ent(name) {\r\n                return location.protocol + \"//\" + location.host + L" +
                        "_Menu_BaseUrl + \"/SiteAssets/projectsitelistviewer/scripts/\" + name;\r\n          " +
                        "  }\r\n            var lpck = 0;\r\n\r\n            function TryGetProjectSiteResult()" +
                        " {\r\n                if (typeof epm == \'undefined\') {\r\n                    setTim" +
                        "eout(function () {\r\n                        if (lpck < 62) {\r\n                  " +
                        "          lpck++;\r\n                            TryGetProjectSiteResult();\r\n     " +
                        "                   }\r\n                    }, 150)\r\n                }\r\n          " +
                        "      else {\r\n                    GetProjectSiteResult();\r\n                }\r\n  " +
                        "          }\r\n            function ParseListName(listName) {\r\n                var" +
                        " rvalue;\r\n                if (listName) {\r\n                    rvalue = listName" +
                        ";\r\n                    var ln = listName.toLowerCase();\r\n                    if " +
                        "(ln == \'issue\' || ln == \'issues\') {\r\n                        rvalue = epm.Projec" +
                        "tSiteListViewer.issues;\r\n                    }\r\n                    else {\r\n    " +
                        "                    if (ln == \'risk\' || ln == \'risks\') {\r\n                      " +
                        "      rvalue = epm.ProjectSiteListViewer.risks;\r\n                        }\r\n    " +
                        "                    else {\r\n                            if (ln == \'documents\' ||" +
                        " ln == \'document\' || ln == \'document library\' || ln == \'shared%20documents\' || l" +
                        "n == \'shared documents\') {\r\n                                rvalue = epm.Project" +
                        "SiteListViewer.documents;\r\n                            }\r\n                      " +
                        "      else {\r\n                                if (ln == \'deliverables\' || ln == " +
                        "\'deliverable\') {\r\n                                    rvalue = epm.ProjectSiteLi" +
                        "stViewer.deliverables;\r\n                                }\r\n                     " +
                        "       }\r\n                        }\r\n                    }\r\n\r\n                }\r" +
                        "\n                else {\r\n                    rvalue = epm.ProjectSiteListViewer." +
                        "risks;\r\n                }\r\n                return rvalue;\r\n            }\r\n      " +
                        "      var projViewer;\r\n            function GetProjectSiteResult() {\r\n          " +
                        "      var loadingImage = getProjectSiteViewerComponent(\'ajax-loader.gif\');\r\n    " +
                        "            projViewer = new epm.ProjectSiteListViewer(this.epmvar.parentDiv, lo" +
                        "adingImage);\r\n                var listToUse = ParseListName(this.epmvar.listName" +
                        ");\r\n                projViewer.get_TargetList(listToUse, this.epmvar.viewName);\r" +
                        "\n            }\r\n\r\n            ExecuteOrDelayUntilScriptLoaded(TryGetProjectSiteR" +
                        "esult, \"sp.js\");\r\n        }\r\n    })();\r\n</script>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
